# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import QLabel

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(446, 316)
        self.lableDdaz = QLabel(Dialog)
        self.lableDdaz.setGeometry(QtCore.QRect(30, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lableDdaz.setFont(font)
        self.lableDdaz.setObjectName("lableDdaz")
        self.ddzd = QLabel(Dialog)
        self.ddzd.setGeometry(QtCore.QRect(140, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.ddzd.setFont(font)
        self.ddzd.setText("")
        self.ddzd.setObjectName("ddzd")
        self.lableFcsj = QLabel(Dialog)
        self.lableFcsj.setGeometry(QtCore.QRect(30, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lableFcsj.setFont(font)
        self.lableFcsj.setObjectName("lableFcsj")
        self.fcsj = QLabel(Dialog)
        self.fcsj.setGeometry(QtCore.QRect(140, 60, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.fcsj.setFont(font)
        self.fcsj.setText("")
        self.fcsj.setObjectName("fcsj")
        self.lableShul = QLabel(Dialog)
        self.lableShul.setGeometry(QtCore.QRect(30, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lableShul.setFont(font)
        self.lableShul.setObjectName("lableShul")
        self.shul = QLabel(Dialog)
        self.shul.setGeometry(QtCore.QRect(140, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.shul.setFont(font)
        self.shul.setText("")
        self.shul.setObjectName("shul")
        self.lableHjje = QLabel(Dialog)
        self.lableHjje.setGeometry(QtCore.QRect(30, 160, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lableHjje.setFont(font)
        self.lableHjje.setObjectName("lableHjje")
        self.hjje = QLabel(Dialog)
        self.hjje.setGeometry(QtCore.QRect(140, 160, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.hjje.setFont(font)
        self.hjje.setText("")
        self.hjje.setObjectName("hjje")
        self.lableDqlsh = QLabel(Dialog)
        self.lableDqlsh.setGeometry(QtCore.QRect(10, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lableDqlsh.setFont(font)
        self.lableDqlsh.setObjectName("lableDqlsh")
        self.dqls = QLabel(Dialog)
        self.dqls.setGeometry(QtCore.QRect(140, 210, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.dqls.setFont(font)
        self.dqls.setText("")
        self.dqls.setObjectName("dqls")
        self.lableSysl = QLabel(Dialog)
        self.lableSysl.setGeometry(QtCore.QRect(30, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lableSysl.setFont(font)
        self.lableSysl.setObjectName("lableSysl")
        self.sysl = QLabel(Dialog)
        self.sysl.setGeometry(QtCore.QRect(140, 260, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.sysl.setFont(font)
        self.sysl.setText("")
        self.sysl.setObjectName("sysl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(u'保险信息')
        self.lableDdaz.setText(u'到达站点：')
        self.lableFcsj.setText(u'发车时间：')
        self.lableShul.setText(u'数    量：')
        self.lableHjje.setText(u'合计金额：')
        self.lableDqlsh.setText(u'当前流水号：')
        self.lableSysl.setText(u'单证剩余：')

